### ISSUE TITLE
can_do_timeout support missing.

### ISSUE THREAD

**Issue by JustinAzoff** [YelpArchive/python-gearman#2]
the optional timeout option to register_task is missing... basically the worker can support

```
CAN_DO task
```

and

```
CAN_DO_TIMEOUT task timeout
```

If you don't have time to add this I can probably cook up a patch...

**Comment by mtai** [comment]
I can add this, but I don't think the C-gearman server actually does anything with it.  Try grepping libgearman-server for:

worker->timeout

Is this something you'd still like?  If so I can patch in your request

**Comment by mtai** [comment]
Ping!  Still interested in this implementation?

**Comment by JustinAzoff** [comment]
Yeah.. though as you pointed out the C server doesn't support it either, which makes it kind of pointless..
