### ISSUE TITLE
Logging errors

### ISSUE THREAD

**Issue by aidanlister** [YelpArchive/python-gearman#3]
Hello,

You've got lots of logging stuff which is throwing errors, I think this page might be relevant:
http://docs.python.org/library/logging#configuring-logging-for-a-library

**Comment by mtai** [comment]
Hey that looks good... how can I reproduce the error though?  I'm running with _DEBUG_MODE_ = True with python 2.5 and I'm not seeing any nasty logging printouts.  I agree I should add the NullHandler but I'm not sure how I can test this

**Comment by aidanlister** [comment]
Hrmm I think you'll see errors if there's a problem with the gearman server, I was getting them with the older Perl version of the gearman server. I don't know how you'd go about replicating it. Perhaps add in a few debug log messages, add the nullhandler, then remove them?

**Comment by mtai** [comment]
Closed with python-gearman 2.0.2

Thanks for the bug report!
