### ISSUE TITLE
workers don't wake up

### ISSUE THREAD

**Issue by nbari** [YelpArchive/python-gearman#37]
when launching the workers, they poll the gearmand server for 60 seconds but then they sleep and don't wake up when a job is ready on the server.

If a job is submitted, instead of been processed immediately, the workers take the project after around also 1 min.

Any idea of how to make the workers process all the jobs immediately or to wake them up when a job arrives ?

Jobs I am creating are in background mode

**Comment by nbari** [comment]
If I am right there could be something wrong with the handling of 'NOOP' the version of gearmand that I am using the lastest version 1.1.7

**Comment by klange** [comment]
We are aware of this issue and have a possible fix in testing.

**Comment by nbari** [comment]
Can you share the testing version so that I can also use it and help debugging.?

**Comment by klange** [comment]
Please see the `worker-coaxing` branch in this repository, which does not rely on NOOP responses to request workers. In addition to this, we have a batched worker class that is still in development (which I can not make available at this time) that uses a different workflow and should not be susceptible to issues handling NOOPs.

**Comment by nbari** [comment]
is there a stable working version ? maybe  older versions of germand with any python client release ?

**Comment by klange** [comment]
You may have some luck with an older gearmand, yes.

**Comment by nbari** [comment]
sorry to bother again with this, but any know gearmand release /version that work fine with the  current python client  ? if I am right is more an issue with gearmand that with python right ?

**Comment by nbari** [comment]
I am testing branch worker-coaxing  with gearmand 1.1.7 and working very nice, just curious to know how you handle the  'NOOP's ?

**Comment by chrisvaughn** [comment]
Any update on how testing is going for these changes?  I have run into the same problem and will be using the `worker-coaxing` branch in our dev environment to see how things go.

**Comment by klange** [comment]
The branch has proved promising, but we would like to take a cleaner and more effective approach as there are still some edge cases that lead to the same end result (stuck workers).

**Comment by ninjapenguin** [comment]
Just to add to this thread - we are also experiencing problems with this issue - are you able to elaborate on the known edge cases with `worker-coaxing`? Is the general consensus that it is stable?

**Comment by yunjianfei** [comment]
There are some bugs with  worker-coaxing  that  work with mutiple gearman servers,  noop received ,will get job lock, There only have one lock, but there are many noop for mutiple servers. 

So. only one server can received GRAB_JOB_UNIQ . Other NOOP handler can't get lock, and go to sleep.

I have resolved this problem, gather some code from the branches. Add some code to grab job from servers.

My fork is https://github.com/yunjianfei/python-gearman
