### ISSUE TITLE
Exceptions are swallowed

### ISSUE THREAD

**Issue by viraptor** [YelpArchive/python-gearman#4]
If some exception is raised inside of the worker, the python-gearman just ignores it. The job is completed as failed, but the worker does not report anything at all.
Some message via logging at least would be good.

**Comment by mtai** [comment]
You can override the "on_job_exception" method on the worker to do whatever logging you'd like.

**Comment by viraptor** [comment]
Shouldn't there be a default for people who miss it? I mean, the only place it's mentioned in the documentation is the "Transitioning from python-gearman 1.x to 2.0.0" page, which is not something I'd try, while trying to solve a problem in 2.0.0 for the first time.
Printing out the exception via logging would at least give some more feedback than "it suddently stops" and can be still overridden in custom code. Right now, it's just quietly failing, which can waste considerable amount of time for someone not knowing this (I know it did almost a day of mine).

**Comment by BrianAker** [comment]
FWIW in 1.2 you can tell the gearmand server to automatically enable these.
