### ISSUE TITLE
Links are broken in README.txt

### ISSUE THREAD

**Issue by splaice** [YelpArchive/python-gearman#5]
- 2.x source <http://github.com/Yelp/python-gearman/&gt;
- 2.x documentation <http://packages.python.org/gearman/&gt;
- 1.x source <http://github.com/samuel/python-gearman/&gt;
- 1.x documentation <http://github.com/samuel/python-gearman/tree/master/docs/&gt;

Remove &gt from the end.

**Comment by mtai** [comment]
I don't see how this is a problem... the ">" seems to render fine in GitHub AND in my text editor.

**Comment by splaice** [comment]
They are working properly for me now, github bug?
