### ISSUE TITLE
Memory Leak found

### ISSUE THREAD

**Issue by peick** [YelpArchive/python-gearman#6]
If you have a gearman client like the one below and you want to submit many jobs, then you run into a memory leak.

client = gearman.GearmanClient(server)
for job in many_many_jobs:
  req = client.submit_job(task, data) ...

The problem is in the python module client_handler.py, where every job is stored in a dictionary but never deleted.

**Comment by mtai** [comment]
Working on a patch that should help alleviate (but not completely) solve your problem.

**Comment by mtai** [comment]
Closed with python-gearman 2.0.2

Thanks for the bug report!
