### ISSUE TITLE
Contact address in copyright information

### ISSUE THREAD

**Issue by oxan** [YelpArchive/python-gearman#8]
Hi,

I'm packaging your software for including it in Debian, but have some questions about the copyright:
- I assume from the LICENSE.TXT file that the company is copyright holder for the software, am I right?
- It would be nice to have a contact address added to the copyright.

Thanks!

**Comment by mtai** [comment]
I took a look at

http://apache.org/licenses/LICENSE-2.0

and it doesn't seem to have any requirements for address.  I've gone ahead and contacted legal and I have something I can add but I'm not sure where in the license I'm supposed to put an address.  Why do you need an address these days?

**Comment by oxan** [comment]
No, I mainly meant a contact address (e-mail is fine) where we could reach you (for example when github closes or something). Usually it states something like "copyright &lt;year&gt; &lt;name company/person&gt; &lt;e-mail address&gt;".

(update 20/02: fix some markup which treated text as html)

**Comment by oxan** [comment]
Oh, just noticed that I closed this by accident. They really shouldn't make the close button so big without a method to reopen...

**Comment by eskil** [comment]
Better late than never, added an email address.
